### ISSUE TITLE
Comments in javadoc format

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-games-pong#20]
There are many good comments in this project; however in many cases they are only comments that use the single line `//` format. Refactor these to use javadoc comments with appropriate annotations such as `@author`, `@version` and `@see` for class-level javadocs and `@param` and others for method-level javadocs. This is a good way to become familiar with the code for new developers on this project.

~estimated 100

**Comment by vincegando** [comment]
Completed. VG & KL
