### ISSUE TITLE
Add "pause game" functionality

### ISSUE THREAD

**Issue by kjorg50** [UCSB-CS56-Projects/cs56-games-pong#22]
Add the ability to pause the game during gameplay. Also add the ability to return to the main menu when paused. See [the pacman game](https://github.com/UCSB-CS56-Projects/cs56-games-pacman) for an example.

~estimated 200

**Comment by vincegando** [comment]
Completed. Talked with Daniel, he agreed to give us 250 points for this. VG & KL
