### ISSUE TITLE
Game menu uses paint graphics instead of default Java Buttons

### ISSUE THREAD

**Issue by agortega** [UCSB-CS56-Projects/cs56-games-pong#43]
Game menu could use graphics instead of defaulting to the default button widgets.

**Comment by agortega** [comment]
400pts

**Comment by omeedrabani** [comment]
Approved: 350 pts

**Comment by agortega** [comment]
* Ended up adding boilerplate for padding the menu.
* Responsiveness via Text selection and menu sounds
* Required refactoring the whole menu logic, because there was a dependency on the difficultylevel selection. It was attached to the old menu.
