### ISSUE TITLE
Bug: Potential lag from audio collision

### ISSUE THREAD

**Issue by agortega** [UCSB-CS56-Projects/cs56-games-pong#47]
Bug: Sometimes lag is experienced in game when audio collision happens

Note: If no lag is experienced, this may be a time drainer and waste of time. Problem only occurs sometimes.

If lag is experienced in audio collision then prevent this lag.
Use OOP principles to ensure optimization, no memory leaks, and DRY behavior.

**Comment by agortega** [comment]
150 pts

**Comment by omeedrabani** [comment]
Approved: 150 pts

**Comment by omeedrabani** [comment]
W16 OK

**Comment by zhanchengqian** [comment]
F16 OK
