### ISSUE TITLE
Feature: Paddles can grab the pong-ball and let go when desired.

### ISSUE THREAD

**Issue by agortega** [UCSB-CS56-Projects/cs56-games-pong#51]
The paddles can grab a pong-ball when a key is held, the moment the ball hits the paddle.
This allows for the paddle to change position and control the direction of the ball to the opponent.

**Comment by agortega** [comment]
300 pts

**Comment by omeedrabani** [comment]
W16 OK

**Comment by zhanchengqian** [comment]
F16 OK
