### ISSUE TITLE
Grabbing ball and colliding with wall 

### ISSUE THREAD

**Issue by millanbatra** [UCSB-CS56-Projects/cs56-games-pong#70]
Ball shifts up/down on paddle (depending on upper or lower wall collision while being held to paddle) thus changing ball's position on paddle. If ball is held and user continuously hits top and bottom wall, ball is eventually vertically separated from the paddle while still being held. Though game is still entirely functional, this creates minor glitches when ball makes contact with top or bottom wall while seperated from paddle.

100-200pts

**Comment by zhanchengqian** [comment]
F16 OK (250 pts)

**Comment by joelbagan** [comment]
When player 2 grabs the ball, If player 1 moves their paddle up or down, the ball moves along with player 1.

F17 OK (200pts)
