### ISSUE TITLE
Add new instructions based on new features added. 

### ISSUE THREAD

**Issue by ngonalex** [UCSB-CS56-Projects/cs56-games-pong#71]
A couple new features were added from the old pong version. First, there's a new grab ball feature, when the ball is close enough to a paddle pressing a or the left arrow key (left and right users respectively)  will "stick" the ball to the wall. Additionally, a new game mode with 2 balls has been added. Also could add somethings detailing changes between difficulty level (paddle size, starting ball speed, starting ball size, and window size)

100 pts

**Comment by zhanchengqian** [comment]
F16 OK

**Comment by joelbagan** [comment]
F17 OK 100pts
