### ISSUE TITLE
Bug: Fix how the game recognizes pausing

### ISSUE THREAD

**Issue by ngonalex** [ucsb-cs56-projects/cs56-games-pong#73]
With the new grab ball feature, when the game recognizes that the ball is in range and can be grabbed, the ball's X and Y velocity are set to 0. The pause works by looking at when the ball's velocity X and Y are 0. This has a bandage fix right now checking if the ball is "attached" to the paddle, but occasionally this will bug out especially when the paddle hits the wall (see issue #70 )

150 pts

**Comment by zhanchengqian** [comment]
F16 OK

**Comment by joelbagan** [comment]
F17 OK

**Comment by brianslee** [comment]
...This should be closed now.
