### ISSUE TITLE
Make Two Balls A Fully Customizable Game Mode

### ISSUE THREAD

**Issue by millanbatra** [UCSB-CS56-Projects/cs56-games-pong#74]
As of now we have one game mode that allows for two balls and multiple game modes for a specific difficulty. Find a way to make it so that game mode two balls, which can be renamed to "Customizable Game Mode"  includes any of the difficulty levels we implemented as well as any number of balls between one and 5(after that the game might get unplayable or the balls might not fit on the screen)
200-300pts

**Comment by zhanchengqian** [comment]
F16 OK

**Comment by joelbagan** [comment]
F17 OK 200pts
