### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by joelbagan** [ucsb-cs56-projects/cs56-games-pong#77]
Add a section to the top of the README.md which includes:

1. a project description
2. A quick tutorial of how to run, and interact with the program
3. Screenshots

All of this information/material is available in the README.md, so read through it (as you should do regardless) and organize the information for yourselves and future students.

50pts

**Comment by joelbagan** [comment]
F17 OK (50pts)

**Comment by brianslee** [comment]
Again, it was fixed. WTF
