### ISSUE TITLE
Update and maintain javadoc

### ISSUE THREAD

**Issue by joelbagan** [ucsb-cs56-projects/cs56-games-pong#79]
Add javadoc comments where there are none, and be sure to update javadoc comments where necessary (anywhere you change code/functionality). 

I recommend working on this issue early to get a thorough understanding of the project as whole. I also recommend that you try to keep the javadoc comments updated **as much as possible** not only so you are constantly reviewing your code, but also to prevent yourselves from falling behind and confusing yourselves with outdated information (speaking from my own experience).

150pts

**Comment by joelbagan** [comment]
F17 OK (100pts)

**Comment by brianslee** [comment]
Fixed. Closed W18
