### ISSUE TITLE
Grabbing ball always sets ball velocity direction to left

### ISSUE THREAD

**Issue by joelbagan** [ucsb-cs56-projects/cs56-games-pong#90]
Currently, when grabbing the ball, its velocity direction is immediately set to left. This functionality works fine for the player on the right, but not for the player on the left. When the left player grabs the ball, they can infinitely grab, release, let the ball hit the paddle, and grab again. 

Fix this bug by setting the ball's direction to the direction opposite of the side on which it was grabbed.

F17 OK (50pts)

**Comment by brianslee** [comment]
Fixed.
